startCommand: "gunicorn run:app --bind 0.0.0.0:$PORT"
services:
  - type: web
    name: quiniela-2026-mx
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9